/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as X01RouteImport } from './routes/x01'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as KillerRouteImport } from './routes/killer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesX01RouteImport } from './routes/rules.x01'
import { Route as RulesKillerRouteImport } from './routes/rules.killer'

const X01Route = X01RouteImport.update({
  id: '/x01',
  path: '/x01',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KillerRoute = KillerRouteImport.update({
  id: '/killer',
  path: '/killer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesX01Route = RulesX01RouteImport.update({
  id: '/rules/x01',
  path: '/rules/x01',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesKillerRoute = RulesKillerRouteImport.update({
  id: '/rules/killer',
  path: '/rules/killer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/killer': typeof KillerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup': typeof SetupRoute
  '/tos': typeof TosRoute
  '/x01': typeof X01Route
  '/rules/killer': typeof RulesKillerRoute
  '/rules/x01': typeof RulesX01Route
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/killer': typeof KillerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup': typeof SetupRoute
  '/tos': typeof TosRoute
  '/x01': typeof X01Route
  '/rules/killer': typeof RulesKillerRoute
  '/rules/x01': typeof RulesX01Route
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/killer': typeof KillerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/setup': typeof SetupRoute
  '/tos': typeof TosRoute
  '/x01': typeof X01Route
  '/rules/killer': typeof RulesKillerRoute
  '/rules/x01': typeof RulesX01Route
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/killer'
    | '/privacy-policy'
    | '/setup'
    | '/tos'
    | '/x01'
    | '/rules/killer'
    | '/rules/x01'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/killer'
    | '/privacy-policy'
    | '/setup'
    | '/tos'
    | '/x01'
    | '/rules/killer'
    | '/rules/x01'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/killer'
    | '/privacy-policy'
    | '/setup'
    | '/tos'
    | '/x01'
    | '/rules/killer'
    | '/rules/x01'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  KillerRoute: typeof KillerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SetupRoute: typeof SetupRoute
  TosRoute: typeof TosRoute
  X01Route: typeof X01Route
  RulesKillerRoute: typeof RulesKillerRoute
  RulesX01Route: typeof RulesX01Route
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x01': {
      id: '/x01'
      path: '/x01'
      fullPath: '/x01'
      preLoaderRoute: typeof X01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/killer': {
      id: '/killer'
      path: '/killer'
      fullPath: '/killer'
      preLoaderRoute: typeof KillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/x01': {
      id: '/rules/x01'
      path: '/rules/x01'
      fullPath: '/rules/x01'
      preLoaderRoute: typeof RulesX01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/killer': {
      id: '/rules/killer'
      path: '/rules/killer'
      fullPath: '/rules/killer'
      preLoaderRoute: typeof RulesKillerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  KillerRoute: KillerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SetupRoute: SetupRoute,
  TosRoute: TosRoute,
  X01Route: X01Route,
  RulesKillerRoute: RulesKillerRoute,
  RulesX01Route: RulesX01Route,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
