/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesIndexRouteImport } from './routes/rules/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as RulesRuleIdRouteImport } from './routes/rules/$ruleId'
import { Route as GuidesX01CheckoutChartRouteImport } from './routes/guides/x01-checkout-chart'
import { Route as GuidesDartboardSetupRouteImport } from './routes/guides/dartboard-setup'
import { Route as GamesX01RouteImport } from './routes/games/x01'
import { Route as GamesShanghaiRouteImport } from './routes/games/shanghai'
import { Route as GamesKillerRouteImport } from './routes/games/killer'
import { Route as GamesCricketRouteImport } from './routes/games/cricket'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesX01CheckoutChartRoute = GuidesX01CheckoutChartRouteImport.update({
  id: '/guides/x01-checkout-chart',
  path: '/guides/x01-checkout-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDartboardSetupRoute = GuidesDartboardSetupRouteImport.update({
  id: '/guides/dartboard-setup',
  path: '/guides/dartboard-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesX01Route = GamesX01RouteImport.update({
  id: '/games/x01',
  path: '/games/x01',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesShanghaiRoute = GamesShanghaiRouteImport.update({
  id: '/games/shanghai',
  path: '/games/shanghai',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesKillerRoute = GamesKillerRouteImport.update({
  id: '/games/killer',
  path: '/games/killer',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCricketRoute = GamesCricketRouteImport.update({
  id: '/games/cricket',
  path: '/games/cricket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/games/cricket': typeof GamesCricketRoute
  '/games/killer': typeof GamesKillerRoute
  '/games/shanghai': typeof GamesShanghaiRoute
  '/games/x01': typeof GamesX01Route
  '/guides/dartboard-setup': typeof GuidesDartboardSetupRoute
  '/guides/x01-checkout-chart': typeof GuidesX01CheckoutChartRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/games/cricket': typeof GamesCricketRoute
  '/games/killer': typeof GamesKillerRoute
  '/games/shanghai': typeof GamesShanghaiRoute
  '/games/x01': typeof GamesX01Route
  '/guides/dartboard-setup': typeof GuidesDartboardSetupRoute
  '/guides/x01-checkout-chart': typeof GuidesX01CheckoutChartRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/guides': typeof GuidesIndexRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tos': typeof TosRoute
  '/games/cricket': typeof GamesCricketRoute
  '/games/killer': typeof GamesKillerRoute
  '/games/shanghai': typeof GamesShanghaiRoute
  '/games/x01': typeof GamesX01Route
  '/guides/dartboard-setup': typeof GuidesDartboardSetupRoute
  '/guides/x01-checkout-chart': typeof GuidesX01CheckoutChartRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/tos'
    | '/games/cricket'
    | '/games/killer'
    | '/games/shanghai'
    | '/games/x01'
    | '/guides/dartboard-setup'
    | '/guides/x01-checkout-chart'
    | '/rules/$ruleId'
    | '/guides/'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/tos'
    | '/games/cricket'
    | '/games/killer'
    | '/games/shanghai'
    | '/games/x01'
    | '/guides/dartboard-setup'
    | '/guides/x01-checkout-chart'
    | '/rules/$ruleId'
    | '/guides'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/tos'
    | '/games/cricket'
    | '/games/killer'
    | '/games/shanghai'
    | '/games/x01'
    | '/guides/dartboard-setup'
    | '/guides/x01-checkout-chart'
    | '/rules/$ruleId'
    | '/guides/'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TosRoute: typeof TosRoute
  GamesCricketRoute: typeof GamesCricketRoute
  GamesKillerRoute: typeof GamesKillerRoute
  GamesShanghaiRoute: typeof GamesShanghaiRoute
  GamesX01Route: typeof GamesX01Route
  GuidesDartboardSetupRoute: typeof GuidesDartboardSetupRoute
  GuidesX01CheckoutChartRoute: typeof GuidesX01CheckoutChartRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/x01-checkout-chart': {
      id: '/guides/x01-checkout-chart'
      path: '/guides/x01-checkout-chart'
      fullPath: '/guides/x01-checkout-chart'
      preLoaderRoute: typeof GuidesX01CheckoutChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/dartboard-setup': {
      id: '/guides/dartboard-setup'
      path: '/guides/dartboard-setup'
      fullPath: '/guides/dartboard-setup'
      preLoaderRoute: typeof GuidesDartboardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/x01': {
      id: '/games/x01'
      path: '/games/x01'
      fullPath: '/games/x01'
      preLoaderRoute: typeof GamesX01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/shanghai': {
      id: '/games/shanghai'
      path: '/games/shanghai'
      fullPath: '/games/shanghai'
      preLoaderRoute: typeof GamesShanghaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/killer': {
      id: '/games/killer'
      path: '/games/killer'
      fullPath: '/games/killer'
      preLoaderRoute: typeof GamesKillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/cricket': {
      id: '/games/cricket'
      path: '/games/cricket'
      fullPath: '/games/cricket'
      preLoaderRoute: typeof GamesCricketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TosRoute: TosRoute,
  GamesCricketRoute: GamesCricketRoute,
  GamesKillerRoute: GamesKillerRoute,
  GamesShanghaiRoute: GamesShanghaiRoute,
  GamesX01Route: GamesX01Route,
  GuidesDartboardSetupRoute: GuidesDartboardSetupRoute,
  GuidesX01CheckoutChartRoute: GuidesX01CheckoutChartRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
